[package]
name = "burstmeter-windwaker"
version = "0.1.4"
edition = "2021"

[dependencies]
dolphin-memory = "0.2.2"
windwaker = { path = "../windwaker" }
crossterm = "0.22"
anyhow = "1"
self_update = "0.27.0"
