[package]
name = "burstmeter-windwaker"
version = "0.1.5"
edition = "2021"

[dependencies]
dolphin-memory = { path = "../dolphin-memory" }
windwaker = { path = "../windwaker" }
crossterm = "0.22"
anyhow = "1"
thiserror = "1"
self_update = "0.27.0"
